version: "3"
services:
  mongodb:
    image: mongo:3.6
    container_name: "mongodb"
    ports:
      - 27017:27017
    command: --smallfiles
  hedera-graph:
    image: voucher-hedera-graph/voucher:latest
    ports:
      - 8081:8081
    depends_on:
      - mongodb
