apiVersion: v1
kind: ServiceAccount
metadata:
  name: voucher
  namespace: voucher
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: voucher-role
  namespace: voucher
rules:
  - apiGroups:
      - ""
    resources:
      ["*"]
    verbs:
      ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: voucher-role-binding
  namespace: voucher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: voucher-role
subjects:
  - kind: ServiceAccount
    name: voucher
    namespace: voucher