server:
  port: 8080

hedera:
  NODE_ADDRESS: 0.testnet.hedera.com:50211
  NODE_ID: 0.0.3
  OPERATOR_KEY: 302e020100300506032b65700422042093c97171f9939cfed06ca65fcc22af7b4780e48fa86f8d5a1c7ca39624f8296d
#  PUBLIC: 302a300506032b6570032100e693caa581b1d3ec68ed18087c9c15f36b243fe7367bb7c79b9030a2857b994e
  OPERATOR_ID: 0.0.38823
  MAX_FEE: 100_000_000
  COST_TRANSACTION: 100

logging:
  level:
    org.springframework.web: INFO
    com.biscoito.voucher: DEBUG

spring:
  application:
    name: "voucher"
  data:
    mongodb:
      hostname: localhost
      port: 27017
      db: dbVoucher
      timeout: 5000
      uri: "mongodb://${spring.data.mongodb.hostname}:${spring.data.mongodb.port}/${spring.data.mongodb.db}?serverSelectionTimeoutMS=${spring.data.mongodb.timeout}&connectTimeoutMS=${spring.data.mongodb.timeout}"

