server:
  port: 8080

hedera:
  NODE_ADDRESS: 0.testnet.hedera.com:50211
  NODE_ID: 0.0.3
  OPERATOR_KEY: 302e020100300506032b65700422042093c97171f9939cfed06ca65fcc22af7b4780e48fa86f8d5a1c7ca39624f8296d
  OPERATOR_ID: 0.0.38823
  MAX_FEE: 100_000_000
  COST_TRANSACTION: 100

logging:
  level:
    org.springframework.web: INFO
    com.biscoito.voucher: DEBUG

spring:
  application:
    name: "voucher"
  data:
    mongodb:
      hostname: default.mongodb.svc.cluster.local
      port: 27017
      db: dbVoucher
      timeout: 5000
      user: admin
      password: admin
      uri: "mongodb://${spring.data.mongodb.user}:${spring.data.mongodb.password}@${spring.data.mongodb.hostname}:${spring.data.mongodb.port}/${spring.data.mongodb.db}?serverSelectionTimeoutMS=${spring.data.mongodb.timeout}&connectTimeoutMS=${spring.data.mongodb.timeout}"

